import { useEffect, useRef, useState } from "react";
import { AlertCircle, ArrowRight, Mic, MicOff, ShieldCheck, Sparkles, User, Video, VideoOff } from "lucide-react";

export function LobbyPage({ stream, mediaError, username, setUsername, connect, videoEnabled, audioEnabled, toggleVideo, toggleAudio }) {
  const videoRef = useRef(null);
  const [isConnecting, setIsConnecting] = useState(false);
  const [joinError, setJoinError] = useState("");
  useEffect(() => { if (videoRef.current) videoRef.current.srcObject = stream; }, [stream, videoEnabled]);
  const handleConnect = async () => {
    if (!username.trim() || !stream) return;
    setIsConnecting(true); setJoinError("");
    try { await connect(); } catch (error) { setJoinError(error.message); setIsConnecting(false); }
  };

  return <div className="relative flex min-h-dvh flex-col overflow-hidden bg-slate-950 text-white">
    <nav className="flex min-h-16 items-center justify-between border-b border-white/10 px-4 sm:px-6"><div className="flex items-center gap-2.5"><div className="flex size-9 items-center justify-center rounded-xl bg-blue-600"><Video className="size-5" /></div><span className="text-xl font-bold">AuraMeet</span></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold text-emerald-300">Secure lobby</span></nav>
    <main className="flex flex-1 items-center justify-center px-4 py-8 sm:px-6 lg:py-12"><div className="grid w-full max-w-6xl items-center gap-8 lg:grid-cols-[1.25fr_0.75fr] lg:gap-14">
      <section className="space-y-4"><div className="flex items-end justify-between"><div><p className="mb-1 text-xs font-bold uppercase tracking-[0.18em] text-cyan-400">Preview</p><h2 className="text-2xl font-bold">Look and sound your best</h2></div><ShieldCheck className="size-5 text-emerald-400" /></div>
        <div className="relative aspect-video overflow-hidden rounded-2xl border border-white/10 bg-slate-900">{stream && videoEnabled ? <video ref={videoRef} autoPlay muted playsInline className="h-full w-full -scale-x-100 object-cover" /> : <div className="flex h-full flex-col items-center justify-center gap-3"><div className="flex size-20 items-center justify-center rounded-full bg-slate-800"><User className="size-8 text-slate-400" /></div><span className="text-sm text-slate-400">{stream ? "Camera is off" : "Preparing camera…"}</span></div>}{username && <div className="absolute bottom-3 left-3 rounded-lg bg-slate-950/80 px-3 py-1.5 text-xs font-semibold">{username}</div>}</div>
        {mediaError && <p role="alert" className="flex items-start gap-2 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200"><AlertCircle className="mt-0.5 size-4 shrink-0" />{mediaError}</p>}
        <div className="flex gap-3"><button type="button" onClick={toggleVideo} disabled={!stream} className={`flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border text-sm font-semibold disabled:opacity-40 ${videoEnabled ? "border-white/10 bg-slate-800" : "border-red-400/30 bg-red-500/15 text-red-300"}`}>{videoEnabled ? <Video className="size-4" /> : <VideoOff className="size-4" />}{videoEnabled ? "Camera on" : "Camera off"}</button><button type="button" onClick={toggleAudio} disabled={!stream} className={`flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border text-sm font-semibold disabled:opacity-40 ${audioEnabled ? "border-white/10 bg-slate-800" : "border-red-400/30 bg-red-500/15 text-red-300"}`}>{audioEnabled ? <Mic className="size-4" /> : <MicOff className="size-4" />}{audioEnabled ? "Mic on" : "Mic off"}</button></div>
      </section>
      <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-6 sm:p-8"><div className="mb-6 flex size-11 items-center justify-center rounded-xl bg-blue-600/15 text-cyan-400"><Sparkles className="size-5" /></div><h1 className="text-3xl font-bold sm:text-4xl">Ready to join?</h1><p className="mt-2 leading-7 text-slate-400">Check your preview, enter a name, and join the room.</p><div className="mt-7"><label htmlFor="display-name" className="mb-2 block text-sm font-semibold text-slate-300">Display name</label><div className="relative"><User className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-slate-500" /><input id="display-name" autoComplete="name" value={username} onChange={(event) => setUsername(event.target.value)} onKeyDown={(event) => event.key === "Enter" && handleConnect()} className="min-h-12 w-full rounded-xl border border-white/10 bg-slate-950 pl-11 pr-4 text-base outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/20" /></div></div>{joinError && <p role="alert" className="mt-3 text-sm text-red-300">{joinError}</p>}<p className="mt-4 flex items-center gap-2 text-sm text-slate-400"><ShieldCheck className="size-4 text-emerald-400" />Your connection is private and secure.</p><button type="button" onClick={handleConnect} disabled={!username.trim() || !stream || isConnecting} className="group mt-7 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 font-bold hover:bg-blue-500 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-400">{isConnecting ? "Joining…" : <>Join meeting<ArrowRight className="size-5" /></>}</button></section>
    </div></main>
  </div>;
}
